Repository SixLabors/Fonts, pull requests merged in 2021-08, with the labels that each got.

#188 Add support for reading woff2 fonts
  README.md
  samples/DrawWithImageSharp/DrawWithImageSharp.csproj
  samples/DrawWithImageSharp/Program.cs
  src/SixLabors.Fonts/BigEndianBinaryReader.cs
  src/SixLabors.Fonts/Exceptions/InvalidFontTableException.cs
  src/SixLabors.Fonts/FontDescription.cs
  src/SixLabors.Fonts/FontReader.cs
  src/SixLabors.Fonts/Glyph.cs
  src/SixLabors.Fonts/GlyphLayout.cs
  src/SixLabors.Fonts/GlyphMetrics.cs
  src/SixLabors.Fonts/IDeepCloneable.cs
  src/SixLabors.Fonts/IGlyphRenderer.cs
  src/SixLabors.Fonts/RendererOptions.cs
  src/SixLabors.Fonts/Tables/General/CMapTable.cs
  src/SixLabors.Fonts/Tables/General/ColrTable.cs
  src/SixLabors.Fonts/Tables/General/CpalTable.cs
  src/SixLabors.Fonts/Tables/General/GlyphTable.cs
  src/SixLabors.Fonts/Tables/General/Glyphs/CompositeGlyphFlags.cs
  src/SixLabors.Fonts/Tables/General/Glyphs/CompositeGlyphLoader.cs
  src/SixLabors.Fonts/Tables/General/Glyphs/EmptyGlyphLoader.cs
  src/SixLabors.Fonts/Tables/General/Glyphs/GlyphLoader.cs
  src/SixLabors.Fonts/Tables/General/Glyphs/GlyphVector.cs
  src/SixLabors.Fonts/Tables/General/Glyphs/GlyphVectorWithColor.cs
  src/SixLabors.Fonts/Tables/General/Glyphs/SimpleGlyphLoader.cs
  src/SixLabors.Fonts/Tables/General/Glyphs/TransformedGlyphLoader.cs
  src/SixLabors.Fonts/Tables/General/HeadTable.cs
  src/SixLabors.Fonts/Tables/General/HorizontalHeadTable.cs
  src/SixLabors.Fonts/Tables/General/HorizontalMetricsTable.cs
  src/SixLabors.Fonts/Tables/General/IndexLocationTable.cs
  src/SixLabors.Fonts/Tables/General/KerningTable.cs
  src/SixLabors.Fonts/Tables/General/MaximumProfileTable.cs
  src/SixLabors.Fonts/Tables/General/NameTable.cs
  src/SixLabors.Fonts/Tables/General/OS2Table.cs
  src/SixLabors.Fonts/Tables/General/VerticalHeadTable.cs
  src/SixLabors.Fonts/Tables/General/VerticalMetricsTable.cs
  src/SixLabors.Fonts/Tables/TableFormat.cs
  src/SixLabors.Fonts/Tables/TableHeader.cs
  src/SixLabors.Fonts/Tables/TableLoader.cs
  src/SixLabors.Fonts/Tables/TripleEncodingRecord.cs
  src/SixLabors.Fonts/Tables/TripleEncodingTable.cs
  src/SixLabors.Fonts/Tables/TtcHeader.cs
  src/SixLabors.Fonts/Tables/Woff2TableHeader.cs
  src/SixLabors.Fonts/Tables/Woff2Utils.cs
  src/SixLabors.Fonts/Tables/WoffTableHeader.cs
  src/SixLabors.Fonts/TempGlyph.cs
  src/SixLabors.Fonts/TextMeasurer.cs
  src/SixLabors.Fonts/TextRenderer.cs
  tests/SixLabors.Fonts.Tests/FontCollectionTests.cs
  tests/SixLabors.Fonts.Tests/FontDescriptionTests.cs
  tests/SixLabors.Fonts.Tests/FontLoaderTests.cs
  tests/SixLabors.Fonts.Tests/FontMetricsTests.cs
  tests/SixLabors.Fonts.Tests/FontReaderTests.cs
  tests/SixLabors.Fonts.Tests/Fonts/OpenSans-Regular.woff2
  tests/SixLabors.Fonts.Tests/GlyphTests.cs
  tests/SixLabors.Fonts.Tests/Tables/General/Glyphs/CompositeGlyphLoaderTests.cs
  tests/SixLabors.Fonts.Tests/Tables/General/Glyphs/GlyphVectorTests.cs
  tests/SixLabors.Fonts.Tests/TestFonts.cs
Labels: format:woff2

#192 Allow loading of Non-Windows character maps
  samples/DrawWithImageSharp/DrawWithImageSharp.csproj
  samples/DrawWithImageSharp/Program.cs
  src/SixLabors.Fonts/Tables/General/CMapTable.cs
  src/SixLabors.Fonts/TextLayout.cs
  tests/SixLabors.Fonts.Tests/FontMetricsTests.cs
  tests/SixLabors.Fonts.Tests/Fonts/Helvetica.ttc
  tests/SixLabors.Fonts.Tests/Issues/Issues_180.cs
  tests/SixLabors.Fonts.Tests/Issues/Issues_191.cs
  tests/SixLabors.Fonts.Tests/TestFonts.cs
Labels: bug

#190 Expose methods to get paths for fonts.
  README.md
  samples/DrawWithImageSharp/Program.cs
  samples/ListFonts/Program.cs
  src/SixLabors.Fonts/Exceptions/FontException.cs
  src/SixLabors.Fonts/Exceptions/FontFamilyNotFoundException.cs
  src/SixLabors.Fonts/Exceptions/FontsThrowHelper.cs
  src/SixLabors.Fonts/Exceptions/GlyphMissingException.cs
  src/SixLabors.Fonts/Exceptions/InvalidFontFileException.cs
  src/SixLabors.Fonts/Exceptions/InvalidFontTableException.cs
  src/SixLabors.Fonts/Exceptions/MissingFontTableException.cs
  src/SixLabors.Fonts/Font.cs
  src/SixLabors.Fonts/FontCollection.cs
  src/SixLabors.Fonts/FontFamily.cs
  src/SixLabors.Fonts/FontFamilyCollectionExtensions.cs
  src/SixLabors.Fonts/FontReader.cs
  src/SixLabors.Fonts/IFontCollection.cs
  src/SixLabors.Fonts/IReadonlyFontCollection.cs
  src/SixLabors.Fonts/IReadonlyFontCollectionExtensions.cs
  src/SixLabors.Fonts/IReadonlyFontMetricsCollection.cs
  src/SixLabors.Fonts/RendererOptions.cs
  src/SixLabors.Fonts/StringComparerHelpers.cs
  src/SixLabors.Fonts/SystemFontCollection.cs
  src/SixLabors.Fonts/SystemFonts.cs
  src/SixLabors.Fonts/Tables/General/HeadTable.cs
  src/SixLabors.Fonts/Tables/General/HorizontalHeadTable.cs
  src/SixLabors.Fonts/Tables/General/IndexLocationTable.cs
  src/SixLabors.Fonts/Tables/General/NameTable.cs
  src/SixLabors.Fonts/Tables/General/VerticalHeadTable.cs
  src/SixLabors.Fonts/Tables/TtcHeader.cs
  src/SixLabors.Fonts/Tables/Woff2Utils.cs
  src/SixLabors.Fonts/TextLayout.cs
  tests/SixLabors.Fonts.Tests/Accents.cs
  tests/SixLabors.Fonts.Tests/ConstructorGuards.cs
  tests/SixLabors.Fonts.Tests/FakeFont.cs
  tests/SixLabors.Fonts.Tests/FontCollectionTests.cs
  tests/SixLabors.Fonts.Tests/FontDescriptionTests.cs
  tests/SixLabors.Fonts.Tests/FontFamilyTests.cs
  tests/SixLabors.Fonts.Tests/FontLoaderTests.cs
  tests/SixLabors.Fonts.Tests/FontMetricsTests.cs
  tests/SixLabors.Fonts.Tests/FontReaderTests.cs
  tests/SixLabors.Fonts.Tests/FontTests.cs
  tests/SixLabors.Fonts.Tests/GlyphTests.cs
  tests/SixLabors.Fonts.Tests/Issues/Issues_180.cs
  tests/SixLabors.Fonts.Tests/Issues/Issues_191.cs
  tests/SixLabors.Fonts.Tests/Issues/Issues_23.cs
  tests/SixLabors.Fonts.Tests/Issues/Issues_27.cs
  tests/SixLabors.Fonts.Tests/Issues/Issues_32.cs
  tests/SixLabors.Fonts.Tests/Issues/Issues_33.cs
  tests/SixLabors.Fonts.Tests/Issues/Issues_35.cs
  tests/SixLabors.Fonts.Tests/Issues/Issues_36.cs
  tests/SixLabors.Fonts.Tests/Issues/Issues_39.cs
  tests/SixLabors.Fonts.Tests/Issues/Issues_47.cs
  tests/SixLabors.Fonts.Tests/Issues/Issues_97.cs
  tests/SixLabors.Fonts.Tests/SystemFontCollectionTests.cs
  tests/SixLabors.Fonts.Tests/Tables/General/CMapTableTests.cs
  tests/SixLabors.Fonts.Tests/Tables/General/IndexLocationTableTests.cs
  tests/SixLabors.Fonts.Tests/Tables/General/MaximumProfileTableTests.cs
  tests/SixLabors.Fonts.Tests/Tables/General/NameTableTests.cs
  tests/SixLabors.Fonts.Tests/TextLayoutTests.cs
  tests/SixLabors.Fonts.Tests/TrueTypeCollectionTests.cs
Labels: codequality, api

#189 Expose SpanCodePointEnumerator and SpanGraphemeEnumerator
  src/SixLabors.Fonts/GlyphLayout.cs
  src/SixLabors.Fonts/TextLayout.cs
  src/SixLabors.Fonts/Unicode/CodePoint.cs
  src/SixLabors.Fonts/Unicode/Grapheme.cs
  src/SixLabors.Fonts/Unicode/MemoryExtensions.cs
  src/SixLabors.Fonts/Unicode/SpanCodePointEnumerator.cs
  src/SixLabors.Fonts/Unicode/SpanGraphemeEnumerator.cs
  src/SixLabors.Fonts/Unicode/UnicodeUtility.cs
  tests/SixLabors.Fonts.Tests/Fakes/FakeFontInstance.cs
  tests/SixLabors.Fonts.Tests/Unicode/CodePointTests.cs
  tests/SixLabors.Fonts.Tests/Unicode/GraphemeEnumeratorTests.cs
Labels: unicode, api

#193 Simplify CMapTable implementation
  src/SixLabors.Fonts/Tables/General/CMapTable.cs
Labels: codequality

#194 Fix many typos
  src/SixLabors.Fonts/BigEndianBinaryReader.cs
  src/SixLabors.Fonts/ColorFontSupport.cs
  src/SixLabors.Fonts/Exceptions/FontFamilyNotFoundException.cs
  src/SixLabors.Fonts/Exceptions/GlyphMissingException.cs
  src/SixLabors.Fonts/Exceptions/InvalidFontFileException.cs
  src/SixLabors.Fonts/Font.cs
  src/SixLabors.Fonts/FontMetrics.cs
  src/SixLabors.Fonts/FontRectangle.cs
  src/SixLabors.Fonts/IColorGlyphRenderer.cs
  src/SixLabors.Fonts/IFontCollection.cs
  src/SixLabors.Fonts/IFontMetrics.cs
  src/SixLabors.Fonts/IGlyphRenderer.cs
  src/SixLabors.Fonts/IGlyphRendererExtensions.cs
  src/SixLabors.Fonts/IO/ZlibInflateStream.cs
  src/SixLabors.Fonts/RendererOptions.cs
  src/SixLabors.Fonts/SystemFontCollection.cs
  src/SixLabors.Fonts/SystemFonts.cs
  src/SixLabors.Fonts/Tables/General/CMap/Format12SubTable.cs
  src/SixLabors.Fonts/Tables/General/Colr/BaseGlyphRecord.cs
  src/SixLabors.Fonts/Tables/General/CpalTable.cs
  src/SixLabors.Fonts/Tables/General/HeadTable.cs
  src/SixLabors.Fonts/Tables/General/IndexLocationTable.cs
  src/SixLabors.Fonts/Tables/General/Kern/Format0SubTable.cs
  src/SixLabors.Fonts/Tables/General/Kern/KerningPair.cs
  src/SixLabors.Fonts/Tables/General/NameTable.cs
  src/SixLabors.Fonts/Tables/General/OS2Table.cs
  src/SixLabors.Fonts/Tables/TableLoader.cs
  src/SixLabors.Fonts/TextLayout.cs
  src/SixLabors.Fonts/Unicode/GraphemeClusterClass.cs
  src/SixLabors.Fonts/Unicode/LineBreakClass.cs
  src/SixLabors.Fonts/Unicode/LineBreakEnumerator.cs
  src/SixLabors.Fonts/Unicode/SpanGraphemeEnumerator.cs
  src/SixLabors.Fonts/Unicode/TODO/BidiAlgorithm.cs
  src/SixLabors.Fonts/Unicode/TODO/MappedArraySlice{T}.cs
  src/SixLabors.Fonts/VerticalAlignment.cs
  tests/SixLabors.Fonts.Tests/FontDescriptionTests.cs
  tests/SixLabors.Fonts.Tests/GlyphTests.cs
  tests/SixLabors.Fonts.Tests/Issues/Issues_27.cs
  tests/SixLabors.Fonts.Tests/Issues/Issues_33.cs
  tests/SixLabors.Fonts.Tests/Issues/Issues_35.cs
  tests/SixLabors.Fonts.Tests/Issues/Issues_36.cs
  tests/SixLabors.Fonts.Tests/Issues/Issues_47.cs
  tests/SixLabors.Fonts.Tests/RendererOptionsTests.cs
  tests/SixLabors.Fonts.Tests/Tables/General/CMap/Format0SubTableTests.cs
  tests/SixLabors.Fonts.Tests/Tables/General/CMap/Format4SubTableTests.cs
  tests/SixLabors.Fonts.Tests/Tables/General/ColrTableTests.cs
  tests/SixLabors.Fonts.Tests/Tables/General/Glyphs/CompositeGlyphLoaderTests.cs
  tests/SixLabors.Fonts.Tests/Tables/TableLoaderTests.cs
  tests/SixLabors.Fonts.Tests/TextLayoutTests.cs
  tests/SixLabors.Fonts.Tests/TrueTypeCollectionTests.cs
  tests/SixLabors.Fonts.Tests/WriterExtensions.cs
Labels: codequality

#195 Add FontCollection.AddSystemFontCollection
  src/SixLabors.Fonts/FontCollection.cs
  src/SixLabors.Fonts/FontCollectionExtensions.cs
  src/SixLabors.Fonts/IFontMetricsCollection.cs
  src/SixLabors.Fonts/IReadonlyFontMetricsCollection.cs
  src/SixLabors.Fonts/SystemFontCollection.cs
  tests/SixLabors.Fonts.Tests/FakeFont.cs
  tests/SixLabors.Fonts.Tests/FontCollectionTests.cs
  tests/SixLabors.Fonts.Tests/GlyphTests.cs
  tests/SixLabors.Fonts.Tests/Issues/Issues_32.cs
  tests/SixLabors.Fonts.Tests/Issues/Issues_33.cs
  tests/SixLabors.Fonts.Tests/Issues/Issues_35.cs
  tests/SixLabors.Fonts.Tests/Issues/Issues_36.cs
  tests/SixLabors.Fonts.Tests/Issues/Issues_39.cs
  tests/SixLabors.Fonts.Tests/Issues/Issues_47.cs
  tests/SixLabors.Fonts.Tests/SystemFontCollectionTests.cs
  tests/SixLabors.Fonts.Tests/TextLayoutTests.cs
Labels: api

#197 Support Word Breaking.
  samples/DrawWithImageSharp/DrawWithImageSharp.csproj
  src/SixLabors.Fonts/GlyphLayout.cs
  src/SixLabors.Fonts/GlyphMetrics.cs
  src/SixLabors.Fonts/RendererOptions.cs
  src/SixLabors.Fonts/TextLayout.cs
  src/SixLabors.Fonts/TextMeasurer.cs
  src/SixLabors.Fonts/Unicode/UnicodeUtility.cs
  src/SixLabors.Fonts/WordBreaking.cs
  tests/SixLabors.Fonts.Tests/FontMetricsTests.cs
  tests/SixLabors.Fonts.Tests/Issues/Issues_180.cs
  tests/SixLabors.Fonts.Tests/TextLayoutTests.cs
  tests/SixLabors.Fonts.Tests/Unicode/UnicodeUtilityTests.cs
Labels: enhancement, api
