Repository SixLabors/Fonts, pull requests merged in 2021-07, with the labels that each got.

#181 Fallback for badly formed hhea tables
  src/SixLabors.Fonts/FontInstance.cs
  src/SixLabors.Fonts/Tables/General/OS2Table.cs
  tests/SixLabors.Fonts.Tests/Fonts/whitney-book.ttf
  tests/SixLabors.Fonts.Tests/Issues/Issues_180.cs
  tests/SixLabors.Fonts.Tests/TestFonts.cs
Labels: enhancement

#185 Make CodePoint Public
  src/SixLabors.Fonts/GlyphLayout.cs
  src/SixLabors.Fonts/GlyphMetric.cs
  src/SixLabors.Fonts/TextMeasurer.cs
  src/SixLabors.Fonts/Unicode/BidiCharacterType.cs
  src/SixLabors.Fonts/Unicode/BidiClass.cs
  src/SixLabors.Fonts/Unicode/BidiPairedBracketType.cs
  src/SixLabors.Fonts/Unicode/BidiType.cs
  src/SixLabors.Fonts/Unicode/CodePoint.cs
  src/SixLabors.Fonts/Unicode/CodePointEnumerator.cs
  src/SixLabors.Fonts/Unicode/GraphemeClusterClass.cs
  src/SixLabors.Fonts/Unicode/GraphemeEnumerator.cs
  src/SixLabors.Fonts/Unicode/LineBreakClass.cs
  src/SixLabors.Fonts/Unicode/LineBreakEnumerator.cs
  src/SixLabors.Fonts/Unicode/TODO/BidiAlgorithm.cs
  src/SixLabors.Fonts/Unicode/TODO/BidiData.cs
  src/SixLabors.Fonts/Unicode/TODO/BidiRun.cs
  src/SixLabors.Fonts/Unicode/UnicodeUtility.cs
  src/UnicodeTrieGenerator/Generator.cs
  src/UnicodeTrieGenerator/UnicodeTrieGenerator.csproj
  tests/SixLabors.Fonts.Tests/TextLayoutTests.cs
  tests/SixLabors.Fonts.Tests/Unicode/BidiAlgorithmTests.cs
  tests/SixLabors.Fonts.Tests/Unicode/BidiCharacterTests.cs
  tests/SixLabors.Fonts.Tests/Unicode/CodePointTests.TestData.cs
  tests/SixLabors.Fonts.Tests/Unicode/CodePointTests.cs
  tests/SixLabors.Fonts.Tests/Unicode/GraphemeEnumeratorTests.cs
  tests/SixLabors.Fonts.Tests/Unicode/LineBreakEnumeratorTests.cs
  tests/SixLabors.Fonts.Tests/Unicode/UnicodeTypeMaps.cs
Labels: api, unicode

#186 Fix example reading a font description
  README.md
Labels: documentation
