Repository SixLabors/Fonts, pull requests merged in 2022-02, with the labels that each got.

#234 Drop NetStandard 1.3
  Directory.Build.props
  src/SixLabors.Fonts/Buffer{T}.cs
  src/SixLabors.Fonts/FontCollection.cs
  src/SixLabors.Fonts/FontReader.cs
  src/SixLabors.Fonts/IFontCollection.cs
  src/SixLabors.Fonts/IReadonlyFontCollection.cs
  src/SixLabors.Fonts/SixLabors.Fonts.csproj
  src/SixLabors.Fonts/StringComparerHelpers.cs
  src/SixLabors.Fonts/SystemFontCollection.cs
  src/SixLabors.Fonts/SystemFonts.cs
  src/SixLabors.Fonts/Tables/General/NameTable.cs
Labels: build, breaking

#240 Add an overload of `AddSystemFonts`
  src/SixLabors.Fonts/FontCollectionExtensions.cs
  tests/SixLabors.Fonts.Tests/FontCollectionTests.cs
Labels: api

#241 Make HasPathTests a theory instead of a fact
  tests/SixLabors.Fonts.Tests/FontFamilyTests.cs
Labels: unit tests

#245 Fix bad indexing when shaping fractions
  src/SixLabors.Fonts/Tables/AdvancedTypographic/Shapers/DefaultShaper.cs
  tests/SixLabors.Fonts.Tests/TestFonts.cs
  tests/SixLabors.Fonts.Tests/TextLayoutTests.cs
Labels: bug, shaping

#246 Add line recognition
  src/SixLabors.Fonts/TextMeasurer.cs
  tests/SixLabors.Fonts.Tests/TextLayoutTests.cs
Labels: enhancement, api
